name: Deploy React App to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd mon-app
          npm install

      - name: Build React app
        run: |
          cd mon-app
          npm run build

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: thomasfififi
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-3
          SOURCE_DIR: mon-app/build

      - name: Send log to CloudWatch
        run: |
          TIMESTAMP=$(date +%s000)
          LOG_STREAM="build-$(date +%Y-%m-%d-%H-%M-%S)"

          aws logs create-log-stream \
            --log-group-name "/ci/github-actions" \
            --log-stream-name "$LOG_STREAM" \
            --region eu-west-3 || echo "Stream already exists"

          aws logs put-log-events \
            --log-group-name "/ci/github-actions" \
            --log-stream-name "$LOG_STREAM" \
            --log-events timestamp=$TIMESTAMP,message="✅ Déploiement React réussi à $LOG_STREAM"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-3
